embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/characters/character-male-f.glb\"\n"
  "skeleton: \"/assets/models/characters/character-male-f.glb\"\n"
  "animations: \"/assets/models/characters/character-male-f.glb\"\n"
  "default_animation: \"walk\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"colormap\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/models/characters/colormap.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"tex1\"\n"
  "    texture: \"/assets/models/characters/colormap.png\"\n"
  "  }\n"
  "}\n"
  ""
}
