embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/characters/character-zombie-handsout.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"colormap\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/models/props/graveyard/colormap.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"tex1\"\n"
  "    texture: \"/assets/models/props/graveyard/colormap.png\"\n"
  "  }\n"
  "}\n"
  ""
}
